---
- name: Add VLAN Playbook
  hosts: leafs
  vars:
    vlan_list: [30, 31, 32, 45, 5]
  tasks:
    - name: Add VLANs
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ item }}"
            state: active
        state: replaced
      loop: "{{ vlan_list }}"
