---
- name: Configure LAG
  hosts: leafs
  tasks:
    - name: Merge provided LAG attributes with existing device configuration
      arista.eos.eos_lag_interfaces:
        config:
          - name: 2000
            members:
              - member: Ethernet1
                mode: active
              - member: Ethernet2
                mode: active
        state: merged
