---
- name: Upload configlets to CVP
  hosts: cvp1
  tasks:
    - name: Upload configlets to CVP
      arista.cvp.cv_configlet_v3:
        configlets: "{{ configlet_list }}"
        configlets_notes: "Added by an Ansible Playbook"
