configlet_list:
  test_configlet: "alias tonyb3 show ip interface brief"
  MLAG_Left: "{{ lookup('file', '../configlets/static/MLAG_Left.cfg') }}"
  MLAG_Right: "{{ lookup('file', '../configlets/static/MLAG_Right.cfg') }}"

cvp_containers:
  MLAG_Left:
    parentContainerName: Leaf
    configlets:
      - MLAG_Left
  MLAG_Right:
    parentContainerName: Leaf
    configlets: 
      - MLAG_Right

cvp_devices:
  - fqdn: leaf1
    parentContainerName: Leaf
    configlets:
      - ATD-INFRA
      - leaf1-base
      - MLAG_Left
  - fqdn: leaf2
    parentContainerName: Leaf
    configlets: 
      - ATD-INFRA
      - leaf2-base
      - MLAG_Right
  - fqdn: leaf3
    parentContainerName: Leaf
    configlets:
      - ATD-INFRA
      - leaf3-base
      - MLAG_Left
  - fqdn: leaf4
    parentContainerName: Leaf
    configlets:
      - ATD-INFRA
      - leaf4-base
      - MLAG_Right
